### ISSUE TITLE
linux环境下无法连接

### ISSUE THREAD

**Issue by wangwenhuan120** [bailu1901/lockstepserver#11]
window环境客户端和服务器都正常，linux环境下客户端和服务器无法通信，ReadPacket报错：read error: io: read/write on closed pipe，是什么地方配置问题吗？

**Comment by byebyebruce** [comment]
那应该不是代码问题，检查下防火墙？

**Comment by wangwenhuan120** [comment]
> 

已解决，就是防火墙问题
