### ISSUE TITLE
pb_packet.go的第98行的疑问

### ISSUE THREAD

**Issue by ayamzh** [bailu1901/lockstepserver#14]
![image](https://github.com/byebyebruce/lockstepserver/assets/20828679/1ec6a80c-7be1-4f4c-bf98-e5f4f854ee13)
datelen是uin16最大值不应该是65535么，为什么这里判断大于MaxPacketLen(1024)就报错？

**Comment by byebyebruce** [comment]
一种安全机制，不让客户端发太大包攻击服务器。这个MaxPacketLen可以改成自己的配置

**Comment by ayamzh** [comment]
了解~
