### ISSUE TITLE
kcp参数设置

### ISSUE THREAD

**Issue by homike** [bailu1901/lockstepserver#3]
你好，kcp的参数为什么这么设置，我看和kcpturn中的参数好像不太一致？
`          
            kcpConn.SetNoDelay(1, 10, 2, 1)
            kcpConn.SetStreamMode(true)
            // kcpturn (2048, 2048)
            kcpConn.SetWindowSize(4096, 4096)
            // kcpturn (16 * 1024 * 1024)
            kcpConn.SetReadBuffer(4 * 1024 * 1024)
            // kcpturn (16 * 1024 * 1024)
            kcpConn.SetWriteBuffer(4 * 1024 * 1024)
            // kcpturn  (false)
            kcpConn.SetACKNoDelay(true)
`

**Comment by byebyebruce** [comment]
这个你需要分析你的业务场景，和客户端一起定参数
