### ISSUE TITLE
我可总算把这个项目跑起来了

### ISSUE THREAD

**Issue by lcylichenyi** [bailu1901/lockstepserver#6]
在main.go中少一行引用：
_ "github.com/byebyebruce/lockstepserver/example/api"
不然启动不了api的init方法，无法创建房间

同时建议去game.go把MaxReadyTime设置时间长一点，至少60，不然你还没来得及起客户端就超时了

然后这个项目的具体操作方式是：
先
1. 127.0.0.1:10002 打开浏览器,click创建房间，默认成员有1,2两个，一开始测试可以只设置1
2. unity run&build客户端，pc上启动，连接设置127.0.0.1:10086连接
3. 等待加载，成功

**Comment by byebyebruce** [comment]
sorry，我的锅。已经修复了

**Comment by lcylichenyi** [comment]
有个问题想问一下 为什么创建房间不放在KCP的动作里呢？而是额外做了一个http接口

**Comment by byebyebruce** [comment]
> 有个问题想问一下 为什么创建房间不放在KCP的动作里呢？而是额外做了一个http接口

肯定是其他的服务来驱动创建房间，至于接口形式grpc，http，tcp消息什么都可以

**Comment by lcylichenyi** [comment]
能问一下这是为什么吗？保证房间完成创建吗？

**Comment by byebyebruce** [comment]
开房间肯定是某个玩法触发开的，比如匹配成功，或玩家向某个大厅发送创建房间大厅同意创建等
